### ISSUE TITLE
Assign filesystem labels

### ISSUE THREAD

**Issue by versedwildcat** [nix-community/disko#100]
My use case involves a BTRFS partition inside LUKS.
Normally, I could add a label to the filesystem using `btrfs filesystem label /dev/mapper/example my_label` (https://github.com/nix-community/disko/issues/29#issuecomment-1228729489 for other filesystems) 

Is there a way to assign the label using Disko?
I see that in #30 you found a work around to labels, but I'm not sure how/if to utilize part-type for this

Thanks!

**Comment by lilyinstarlight** [comment]
That's actually a filesystem label rather than a partition label, but you should be able to set that via using the `type = "btrfs";` type and setting `extraArgs = "--label my_label";`, kinda like in https://github.com/nix-community/disko/blob/df3a607ad7ee431f4831a51af2c464aa8a8813f4/example/btrfs-subvolumes.nix#L28-L30

**Comment by versedwildcat** [comment]
> That's actually a filesystem label rather than a partition label, but you should be able to set that via using the `type = "btrfs";` type and setting `extraArgs = "--label my_label";`, kinda like in
> 
> https://github.com/nix-community/disko/blob/df3a607ad7ee431f4831a51af2c464aa8a8813f4/example/btrfs-subvolumes.nix#L28-L30

Thanks! Worked great
I'll leave this issue open for another day in case anyone wants to add anything
