### ISSUE TITLE
installation of grub failed for simple efi example

### ISSUE THREAD

**Issue by ghostbuster91** [nix-community/disko#212]
Given the disko config like in the example: https://github.com/nix-community/disko/blob/master/example/simple-efi.nix

and the boot settings:
```nix 
  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.enableCryptodisk = true;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.efiInstallAsRemovable = true;
  # Define on which hard drive you want to install Grub.
  boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only
```

and the installation iso based on 22.11

Installation of nixos fails with following error:

![image](https://user-images.githubusercontent.com/5662622/233770839-6f022aa3-43c2-4cc5-b154-daf3d87f824b.png)

Some additional context:
![image](https://user-images.githubusercontent.com/5662622/233770880-cfe2c51e-12be-43e0-ac28-3e47ff5f1176.png)

*Sorry for images instead of text, but it is hard to copy it from the virtualbox without guest additions that are missing in the installation system*

It works fine, after turning off grub and switching to systemd-boot:
```nix
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot";
  boot.loader.systemd-boot.enable = true;
```

**Comment by phaer** [comment]
The simple-efi example is EFI-only, but having "boot.loader.grub.device" set to a disk instead of "nodev" results in a hybrid legacy-boot/uefi setup, but that fails because grub doesn't find a BIOS boot partition and so it skips the disk, even if the log lines could be clearer.

So either use "nodev" in your grub config, or make sure you have a BIOS boot partition like in  https://github.com/nix-community/disko/blob/master/example/gpt-bios-compat.nix

**Comment by ghostbuster91** [comment]
You are right, I missed that setting in my config. Let me try to quickly verify that it works.

**Comment by ghostbuster91** [comment]
Confirmed, correctly setting `boot.loader.grub.device = "nodev";` fixed the issue.
