### ISSUE TITLE
Disko sets the wrong partition type for the swap partition

### ISSUE THREAD

**Issue by god464** [nix-community/disko#391]
This my disko setting: https://fars.ee/dKd8/nix
After running `nix --extra-experimental-features 'flakes nix-command' run github:nix-community/disko -- --mode disko ./disk/disko-config.nix`, I'll get the partition situation like this: https://fars.ee/4gPJ.png
As you can see, the Swap partition type has been set to `Linux Filesystem' instead of `Linux Swap'.

**Comment by Lassulus** [comment]
you can set type = "8200"; between line 20 and 21 in your config

**Comment by cvoges12** [comment]
Yeah, but disko should still set the correct filesystem type when specified as type swap.

**Comment by iFreilicht** [comment]
@god464 what kind of tool were you using for this? After a bit of research, we might not want to fix this, see https://github.com/util-linux/util-linux/issues/3238#issuecomment-2413152748

Basically, the "partition type" is only useful for differentiating what partitions are used for when they are otherwise the same (like a /home vs a root partition). The more useful field in most cases is "filesystem type" (called FSTYPE in lsblk and other util-linux tools), which actually tells you what the content of a partition is.

**Comment by iFreilicht** [comment]
> If you mean the tool in the screenshot, it's `cfdisk`.

Yes that's what I meant, thank you!

> I know it's usually not significant, but I'm used to using cfdisk, so the partition type feels more intuitive to me.

Yeah I understand that, and I think it's good to fix this on our side to avoid confusion for users. I think the current state of my PR is reasonable, feel free to take a look :)
