### ISSUE TITLE
Should `disko` acknowledge swap partitions (i.e. assist with `mkswap` or `swapon`)?

### ISSUE THREAD

**Issue by mitchmindtree** [nix-community/disko#44]
I'm currently setting up a little server that has 1GB RAM, and upon installation quickly realised I'd need to add some swap!

While `disko` allows for specifying a `"linux-swap"` `fs-type`, it doesn't appear to check for swap partitions or run `mkswap` or `swapon`.

Perhaps we could:

1. Add a check for a `linux-swap` fs-type partition and, if detected, `mkswap` it and
2. Add a `disko.swapon cfg` script for enabling swap for the specified partition?

If interested, I might have a go at this soon.

**Comment by Lassulus** [comment]
sounds good. I guess we should add a new type for swap for extra options. it should probably run mkswap in the mount script, so it can be used during installation? and in the config it should configure `swapdevices = [ { device = dev; } ];`
You can go for it. I would suggest waiting until #43 is merged since it changed the config a bit. Would be nice to also have a test for that!

If you don't want to implement it, I can also do it at some time

**Comment by blaggacao** [comment]
I need help on `./types.nix` in https://github.com/nix-community/disko/pull/51/commits/46624a8ae13ec63bf79317e26a99b64ed7fa00a7

There's a bit too much context in that file... But I guess I can be helpful with:
- kick-starting (done)
- finishing off
- testing (if we can get this feature in quickly)

**Comment by Lassulus** [comment]
I guess adding an example would be nice. to see what possible options we want to support

**Comment by blaggacao** [comment]
Turns out there might be conflicts to deal with one way or the other:
- https://github.com/NixOS/nixpkgs/blob/29fc06773600d3e4638e75ecacbe17cc0325c983/nixos/modules/config/swap.nix#L227
- https://github.com/NixOS/nixpkgs/blob/29fc06773600d3e4638e75ecacbe17cc0325c983/nixos/modules/config/swap.nix#L233

**Comment by Anomalocaridid** [comment]
Would it be possible to have something similar for btrfs swap subvolumes?

**Comment by Lassulus** [comment]
So I guess the swap support is working, for BTRFS swap we have this issue: https://github.com/nix-community/disko/issues/262
