### ISSUE TITLE
zfs support regression: cannot unmount X: not currently mounted

### ISSUE THREAD

**Issue by ghostbuster91** [nix-community/disko#486]
My [disko config](https://github.com/ghostbuster91/dot-files/blob/6ad7b34d732569dc103f4fdaf674fc692b1d9245/machines/focusM2/disko-config.nix#L1) doesn't work anymore with the latest version from master. 

when doing disks setup using:
```
sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko -- --mode disko /tmp/disko-config.nix --arg disks '["/dev/nvme0n1" "/dev/nvme1n1"]'
```

it fails midway with a following error:
```
+ zpool create -f rpool1 -R /mnt -o ashift=12 -o autotrim=on -O atime=off -O canmount=off /dev/mapper/nixos
+ zfs unmount rpool1
cannot unmount `rpool1`: not currently mounted
```

then calling `mount | grep /mnt` returns only standard overlays. 

The regression was introduced somewhere between https://github.com/nix-community/disko/compare/8759b5bf0af8c21685e1da7f20c40eeb79eaeec2...e526d4e6533d006e4386130df7729830770889b3
 
Later I can minimize the issue further but for now I just wanted to start with something.

**Comment by Lassulus** [comment]
maybe https://github.com/nix-community/disko/pull/474 ?

**Comment by phaer** [comment]
I think the umount command as written added #474 is wrong. It only checks wheter the pool is mounted automatically by verifying that .mountpoint isn't "none", but it can also be i.e. "/" with canmount=off if legacy mounts are used as is the case here. 


If I read #474 correctly, just re-ordering the filesystems could circumvent the issue there so we could revert it? Doesn't seem much hackier than the unmount here.

cc @Enzime

**Comment by Lassulus** [comment]
Revert sounds good!

**Comment by Enzime** [comment]
Alternatively, what about adding `|| true` on the end, that way we don’t need to perfectly model ZFS’s mount logic

**Comment by phaer** [comment]
In my understanding, your original issue is more about a case of incorrect ordering of disko?

My idea to avoid having to deal too much with zfs mount logic would be to try to interfere as little as possible with it; so if we can get rid of the special-case umount, and I think we can, that we would be ideal.

Alternatively that conditional clause could check for `canmount` as well. If we go down that route, it should probably become consistent between zpool, fs and volumes, as the shadowing encountered in #474 could affect them as well, i think? 
Ignoring umount errors via `|| true` would IMO lead to even less predictable behavior, so not a huge fan of that :)

**Comment by Enzime** [comment]
My issue is a result of `disko` mounting the root dataset when creating a zpool, which causes issues later as ZFS will refuse to mount an already mounted dataset which will lead to it being shadowed.

It's not really an ordering issue if you're looking at just the mount script as that will mount the root dataset before the children dataset, it's more like the guard condition inside the mount script can't correctly detect whether a partition is correctly mounted (including not being shadowed). I think the idempotence of the mount script can be improved by unmounting everything before attempting to start mounting things, although I'm not sure what other knock on effects that might have, although it would ensure partitions are correctly mounted with the correct options.

To fix this issue, instead of using `|| true`, I'm thinking the easiest fix would be to check if it's mounted with `zfs get mounted <zpool>` before unmounting.
