### ISSUE TITLE
Cannot specify a relative flake path (flake reference '.' is not an absolute path)

### ISSUE THREAD

**Issue by shelvacu** [nix-community/disko#523]
Mostly a convenience thing, the `--flake` option doesn't seem to support relative paths, so `nix run github:nix-community/disko --  --flake .#my-machine` doesn't work.

**Comment by iFreilicht** [comment]
This should be possible since at least 5fd29dfeb3931fa23ea41ea743201ebf8525dc4d, which was released almost two years ago.

Could you specify what you mean by "doesn't work"? What error are you seeing?

When I run it for a machine with a disko configuration:

```console
# nix run nixpkgs#disko -- --dry-run --mode format --flake .#junction
Finished at 11:36:02 after 4s
/nix/store/vzch5yidwylc65ccc7gznp5bnmz6hghc-disko-format
```

When I run it for one without a disko configuration:

```console
# nix run nixpkgs#disko -- --dry-run --mode format --flake .#source
error:
       … while calling the 'abort' builtin

         at /nix/store/7i9l8n6gmg9g2hja42jsc8j7ivjk700p-disko-1.8.0/share/disko/cli.nix:67:8:

           66|     else
           67|       (builtins.abort "neither diskoConfigurations.${flakeAttr} nor nixosConfigurations.${flakeAttr} found");
             |        ^
           68|

       error: evaluation aborted with the following error message: 'neither diskoConfigurations.source nor nixosConfigurations.source found'
```

Hm, actually, that error message is a little misleading. I'll update that.

**Comment by shelvacu** [comment]
I'm sorry, it's been too long, I don't know what I did to cause that anymore. Clearly at the time I thought it just wasn't supported.
