### ISSUE TITLE
Disko requires a `./` for the disko file and gives a cryptic error when missing

### ISSUE THREAD

**Issue by con-f-use** [nix-community/disko#536]
First command doesn't work, second does.

```shell

[root@nixos:~]# disko --mode mount --dry-run --argstr device /dev/sda --root-mountpoint /mnt lvm_btrfs_disko.nix           
error: undefined variable 'lvm_btrfs_disko'

       at «string»:1:1:

            1| lvm_btrfs_disko.nix
             | ^

[root@nixos:~]# disko --mode mount --dry-run --argstr device /dev/sda --root-mountpoint /mnt ./lvm_btrfs_disko.nix 
/nix/store/936rs17s4xvm3bm868s8zvawcn9p6iwv-disko-mount
```

**Comment by iFreilicht** [comment]
Jup, this is still the case with v1.8.0:

```
$ nix run . -- --mode mount --dry-run hybrid.nix
path '/home/felix/repos-new/disko/example' does not contain a 'flake.nix', searching up
disko version 1.8.0-f0544d6
error: undefined variable 'hybrid'

       at «string»:1:1:

            1| hybrid.nix
             | ^

```

This is caused by [disko passing the file as a nix expression](https://github.com/nix-community/disko/blob/d39ee334984fcdae6244f5a8e6ab857479cbaefe/disko#L136) instead of a string. This means `lvm_btrfs_disko.nix` is an expression that accesses the attribute `nix` on the set `lvm_btrfs_disko`, but of course, no such variable exists.

Replicating the error is easy:

```
nix eval --expr "hybrid.nix"
error: undefined variable 'hybrid'
       at «string»:1:1:
            1| hybrid.nix
             | ^
```

The fix is to use `--argstr` instead of `--arg` and change [the import](https://github.com/nix-community/disko/blob/d39ee334984fcdae6244f5a8e6ab857479cbaefe/cli.nix#L49) to convert the string to a path first, but I didn't manage to do this properly and have to go to be now.

If anyone else wants to pick this up, feel free.
