### ISSUE TITLE
extraPostVM docs: recommendation doesn't work, would be potentially destructive if it did

### ISSUE THREAD

**Issue by colemickens** [nix-community/disko#774]
1. The impure script uses $PWD to build the disk image.
2. There's no protections for an existing disk image in "$out".
3. The option documentation for `extraPostVM`:
   i. doesn't work, you can't glob in a script like that
   ii. if it *did* work, would affect *ANY* .raw files in $PWD/"$out" (which could be bad!)
   iii. is just a bit unfortunate, it would be a great place to show the user how to actually *get* the disk image name

I think when I looked the other day, the disk image name isn't straight forward to recompose and isn't stashed. So maybe a way to fix this is to just move the disk name to an exported `system.build.disko...` whatever attribute, and then use it. Then the user can use that attr to reference the image path in `extraPostVM`.

**Comment by iFreilicht** [comment]
> 1. The impure script uses $PWD to build the disk image.

Correct.

> 2. There's no protections for an existing disk image in "$out".

What do you mean by "protections"? Whether they can be overwritten or not? If so, that's by design, so that when you change something in the config and rebuild, you'll get the latest output. Additionally, these disk images can be big, storing them in the Nix Store by default would be a bad idea, though it would certainly be possible to do as an option.

> 3. The option documentation for extraPostVM:
> i. doesn't work, you can't glob in a script like that

Why do you think that's the case? It is absolutely supported by bash and most other shells. Whether it works depends on the command you're calling.

> ii. if it did work, would affect ANY .raw files in $PWD/"$out" (which could be bad!)

Why? `zstd` doesn't overwrite the original. Or am I missing some other potential issue here?

To illustrate those two points:

```console
# ls
asdf.raw  oijooj.raw  qeriu.raw
# zstd --compress ./*raw 
  3 files compressed : 33.98% (  9.03 KiB =>   3.07 KiB)
# ls
asdf.raw  asdf.raw.zst  oijooj.raw  oijooj.raw.zst  qeriu.raw  qeriu.raw.zst
```

> iii. is just a bit unfortunate, it would be a great place to show the user how to actually get the disk image name

Sure, why not.

> I think when I looked the other day, the disk image name isn't straight forward to recompose and isn't stashed. 

Maybe I haven't grasped some detail about how `diskoImagesScript` is built, but shouldn't a simple `lib.attrNames config.disko.devices.disk` work just fine?

Another option would be to specify the output names yourself using the recently added [`imageName`](https://github.com/nix-community/disko/blob/3b778f10eb275573da9f5c8a7a49e774200b87e5/lib/types/disk.nix#L19).

In the content of this script, `lib.concatStringsSep " " (lib.attrNames config.disko.devices.disk)` would be the solution.

**Comment by colemickens** [comment]
> What do you mean by "protections"? ....

I find the script clobbering an existing image to be poor UX, and I find even worse, a recommendation that would just compress every `*.img` in `$out` (`$PWD`) (again, potentially clobbering existing `*.img.zstd`). But maybe I'm picky for wanting scripts to be a bit more cautious, especially when they just act in `$PWD`.

> Why do you think that's the case? It is absolutely supported by bash and most other shells. Whether it works depends on the command you're calling.

Because globs don't work in scripts like that? Try it, it doesn't work.

> Maybe I haven't grasped some detail about how diskoImagesScript is built, but shouldn't a simple lib.attrNames config.disko.devices.disk work just fine?

Thanks, I just had missed this.

I can send a PR to tighten the recommendation down to just act on the built image.

**Comment by iFreilicht** [comment]
> Because globs don't work in scripts like that? Try it, it doesn't work.

I did, and I literally posted the exact command I used and demonstrate that it does indeed work. Please explain what I did wrong there.

**Comment by colemickens** [comment]
Wow. (After some testing, more testing and reading...) I am quite embarrassed. I very much misunderstood limitations around globbing inside shell scripts. My sincere apologies.

I think the recommended `rm $out/*raw` is still a bit wonky, but also, it's maybe splitting hairs at this point, and it's just example test after all.

I'll close this, if I care enough I'll update the example description with the `imageName` or your other suggestion.

Thanks for looking; apologies again for wasting any time.

**Comment by iFreilicht** [comment]
No worries, happens to the best of us :)
