### ISSUE TITLE
Handling of msdos partition tables

### ISSUE THREAD

**Issue by zarelit** [nix-community/disko#812]
Since introducing `type = "gpt"`, I have been getting the warning: "Legacy table is outdated."

I proceeded to convert elements defined as `type = "table"; format = "gpt"` into the new GPT format, but I continue receiving the error for elements that use `type = "table"; format = "msdos"`.

Question: Are MSDOS partition tables deprecated?

I have a physical machine that is partitioned with an MSDOS partition table to ensure compatibility with BIOS, which allows it to find the bootloader and boot properly.

I understand that there is a way to make GPT work with legacy BIOS, but it requires reformatting the first disk, which I would like to avoid.

Could you provide guidance on how to handle this situation? 

Specifically, is there a way to maintain the current MSDOS partition table while avoiding this warning, or would switching to GPT be necessary?

Any advice on avoiding disk reformatting while ensuring boot compatibility would be greatly appreciated.

**Comment by polybluez** [comment]
Well, MSDOS partition tables probably can be called deprecated, but this is such a small implementation detail that I wouldn't bother sweating over it. As for converting to GPT, if you use GRUB you probably would need to make room for an 1 MB BIOS Boot partition after converting and then reinstalling GRUB so that it picks up on partition table change. Please note I'm not a `disko` developer, just merely a user

**Comment by iFreilicht** [comment]
> Question: Are MSDOS partition tables deprecated?

Yes, along with legacy BIOS. As you are probably aware, this is not a decision by disko, but consensus between all the big corporations that produce PC parts. GPT and UEFI are the new standard. Since 2020, Intel and AMD processors don't even support the Legacy Boot option anymore, though I'm uncertain whether that means they can't boot from disks with an MBR partition table at all.

> Specifically, is there a way to maintain the current MSDOS partition table while avoiding this warning, or would switching to GPT be necessary?

Well, you could just not manage that specific drive with disko.

But there is no option to silence the warning, which is probably what you're looking for.

> I understand that there is a way to make GPT work with legacy BIOS, but it requires reformatting the first disk, which I would like to avoid.

Grub and Linux support GPT even when booting from legacy BIOS, you don't need to do any additional work. You can actually [convert an existing hard drive from MBR to GPT without reformatting](https://serverfault.com/a/963179/312091), though it is a bit of a manual process.

> Any advice on avoiding disk reformatting while ensuring boot compatibility would be greatly appreciated.

If all your disks use MBR, you can just ignore the warning. Be aware that we do not maintain the `table` type, and so if you find bugs with it its unlikely that they will be fixed.

If you have many drives that use GPT and only one with MBR, consider not managing the MBR-based drive with disko at all. Just leave it as it is, and add any partitions you want to mount to your configuration's `fileSystems` directly.

Disko currently can't change partition sizes after the fact anyway, it's mostly useful for setting up partitions on empty drives, and if we implement that feature, MBR is unlikely to be supported.

**Comment by zarelit** [comment]
@iFreilicht Thank you for the information! My question was actually about the table element in disko, rather than msdos tables themselves, which I now understand won't be maintained.

Luckily, I only have one MBR disk, and that’s just because it was the easiest way to boot on an MBR-only system. Since it only contains the system (no user data), I might consider converting it to GPT with a BIOS partition in place.

I also love the idea of using disko configuration as a living reference for the disk layout, so I'd prefer to keep it managed that way.

Also, no need to have an option to silence the warning, if the element it's not maintained it's good to have it there as a reminder.

Thank you again—I really appreciate the help! 

@polybluez I was just checking if I could live with disko AND the legacy table, but if I must choose I'm gonna do like you said: keep disko and try to fit the "bios" partition on the first disk so I can still boot with the legacy mode. Thank you!
