### ISSUE TITLE
Using two SSDs as cache for two HDDs with LVM

### ISSUE THREAD

**Issue by xiro-codes** [nix-community/disko#814]
sorry this is the llm prompt and response, tldr i need to add a line to lvm.conf how to do go about that with disko
```
>>> could i combine 2x250gb ssd and 2x1tb hdd to use the ssd as a cache for the hdd in linux

Yes, you can combine two 250GB SSDs and two 1TB HDDs to create a storage solution that uses the SSDs
as a cache for the HDDs in Linux. This is known as a "hybrid" storage configuration, where the 
faster SSDs are used as a cache for the slower HDDs.

To set this up in Linux, you can use a tool called LVM (Logical Volume Manager) to create a single 
logical volume that spans both the SSDs and the HDDs. You can then configure LVM to use the SSDs as 
a cache for the HDDs by setting up a "write-through" policy, which writes data to both the SSDs and 
the HDDs simultaneously.

Here's an example of how you might set this up using LVM:

1. First, create a physical volume (PV) for each disk. In this example, we'll use /dev/sda and 
/dev/sdb for the SSDs, and /dev/sdc and /dev/sdd for the HDDs.
```
sudo pvcreate /dev/sda
sudo pvcreate /dev/sdb
sudo pvcreate /dev/sdc
sudo pvcreate /dev/sdd
```
2. Next, create a volume group (VG) that spans both the SSD and HDD PVs. In this example, we'll call
it "hybrid-storage".
```
sudo vgcreate hybrid-storage /dev/sda /dev/sdb /dev/sdc /dev/sdd
```
3. Now, create a logical volume (LV) that spans the entire VG. In this example, we'll call it 
"root".
```
sudo lvcreate hybrid-storage -n root
```
4. Finally, format the LV as ext4 and mount it to /mnt/hybrid-storage.
```
sudo mkfs.ext4 /dev/mapper/hybrid--storage-root
sudo mount /dev/mapper/hybrid--storage-root /mnt/hybrid-storage
```
5. To configure the write-through policy, you can use the lvm.conf file. Add the following line to 
the "volume_groups" section of the file:
```
hybrid-storage {
    # ... other configuration options here ...
    cache = writethrough

```

**Comment by iFreilicht** [comment]
Be more precise.

**Comment by xiro-codes** [comment]
Simpler info i just want to do the stuff described here https://man.archlinux.org/man/lvmcache.7

**Comment by iFreilicht** [comment]
First off, please do additional research on your own instead of just blindly trusting an LLM to make a good decision for you. Instead of using LVM and putting an ext4 filesystem on top of it, using ZFS or btrfs which implement caching directly might be the better option.

If you're sure that you want to use LVM for this, I'd say your best starting point is [this example](https://github.com/nix-community/disko/blob/master/example/lvm-raid.nix). Take a look at the [lvm_pv](https://github.com/nix-community/disko/blob/master/lib/types/lvm_pv.nix) and [lvm_vg](https://github.com/nix-community/disko/blob/master/lib/types/lvm_vg.nix) types to see what your options are. You might have to call `lvconvert` manually, we don't have a way to do this sort of thing yet.

**Comment by sielicki** [comment]
> First off, please do additional research on your own instead of just blindly trusting an LLM to make a good decision for you. Instead of using LVM and putting an ext4 filesystem on top of it, using ZFS or btrfs which implement caching directly might be the better option.

On principle, you're totally justified in calling out how lazy it is to take up a maintainers limited time by creating a github issue because a piece of software doesn't support a use-case that chatGPT proposed, but on the merits there's a variety of reasons to genuinely prefer generic lvm tiering over other filesystems with native support. 

Example: I have a NAS running nixos atop an old armv7l platform with 512MB of ram. There's no sense in running zfs or btrfs on a system like that. (I later learned that there's no sense in running LVM on a system like that either, but it did at least mostly work.)

**Comment by xiro-codes** [comment]
I am sorry. I do understand that this was non issue and got a little over zealous playing around with ai. With the recent controversy regarding AI bug reports I will be more critical of its output and avoid raising an issue with our doing proper research. Again I do apologize for wasting your valuable time.

**Comment by Mic92** [comment]
We linked to the LVM example. Not using LVM beyond that much. Not sure how to further help here.
